AllCops:
  Exclude:
    - 'db/*/*'
    - 'db/*'
    - 'config/*/*'
    - 'spec/spec_helper.rb'
    - 'bin/*'
    - 'lib/tasks/*'
    - 'script/*'
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space