apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.5
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: root
          - name: POSTGRES_DB
            value: juniorjobs_production
