apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
